### PR TITLE
Added new template's and Updated Readme 

### PR DESCRIPTION
**Pull request by byaruhaf**

### CODE REVIEW

**Comment by byaruhaf** [comment]
@sanmiguel i agree added the $author tag and updated the readme to list all templet commands.

**Comment by jkrukoff** [comment]
Having just spent some time comparing against the official emacs templates, I think they call the bare module template a "lib" template. Might be nice to make naming match. Not sure if it matters with as long as this has been pending, but seemed worth noting.

**Comment by hcs42** [comment]
@byaruhaf Could you squash everything into one commit? After that, I can merge it.

@jkrukoff Consistency sounds nice. What would being a "lib" template mean codewise?

**Comment by jkrukoff** [comment]
Not much. This is what I'm using in the current templating library I've switched to: https://github.com/jkrukoff/dotfiles/blob/master/Linux/.vim-templates/erl_lib.template

**Pull request closed without merging**
